version: "3.2"
services:
  template-serverless-lambda-python:
    container_name: template-serverless-lambda-python
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    privileged: true
    ports:
      - 5000:5000
    networks:
      - service-python
    volumes:
      - ./:/app
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - default
  mysql:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
#    volumes:
#      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: store
      MYSQL_ROOT_PASSWORD: store
    networks:
      - service-python
#  localstack:
#    image: localstack/localstack
#    privileged: true
#    ports:
#      - "4566:4566"
#      - "4567-4582:4567-4582"
#      - "9070:9070"
#      - "8080:8080"
#    environment:
#      SERVICES: sqs,lambda,cloudwatch
#      DOCKER_HOST: unix:///var/run/docker.sock
#      PORT_WEB_UI: 9070
#      LAMBDA_EXECUTOR: docker
#      DEBUG: 1
#      HOSTNAME_EXTERNAL: localstack
#    networks:
#      - service-python
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /tmp/localstack:/tmp/localstack
networks:
  service-python:
    external: true
