components:
  schemas:
    Alive:
      properties:
        app:
          example: I'm alive!
          type: string
      type: object
info:
  title: template-serverless-lambda-python
  version: 1.0.0
openapi: 3.0.2
paths:
  /alive:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alive'
          description: Success response
      summary: Service Health Method
servers:
- description: Staging server
  url: https://localhost:5000
- description: Development server
  url: http://localhost:5000
